### ISSUE TITLE
about pre_training stage

### ISSUE THREAD

**Issue by hebing-sjtu** [ChenYutongTHU/SplatFormer#12]
Hi, authors. Great work! 

I have a question about the model training. [https://github.com/ChenYutongTHU/SplatFormer/blob/ca0eeb98d6b83a1d8e431f06bb7c0e41e59c4890/utils/gs_utils.py#L118](url)  I'm not sure I understand correctly. It seems the pretraining stage targets isotropic, complete non-transparent, 3D Gaussians with identical size. Could you explain why this was chosen as an intermediate target? Also, I can't find the gin configuration mentioned in the allowlist  . Could you please point it out?

**Comment by ChenYutongTHU** [comment]
Hello.

Thanks for your question.

This is actually a deprecated function. Previously, it was used to pretrain SplatFormer for the first 100 steps so that the model can produce some good 3DGS initialization before the photometric supervision. However, now we initialize model by zero-ing the last FC layers so that the initial predicted residual is zero and the initial output 3DGS is equal to the input flawed 3dGS.
https://github.com/ChenYutongTHU/SplatFormer/blob/ca0eeb98d6b83a1d8e431f06bb7c0e41e59c4890/configs/model/ptv3.gin#L12

The pretraining is not used anymore.
https://github.com/ChenYutongTHU/SplatFormer/blob/ca0eeb98d6b83a1d8e431f06bb7c0e41e59c4890/configs/train/default.gin#L4

Feel free to let me know if you have any questions.

**Comment by hebing-sjtu** [comment]
Thank you for your quick and detailed response. Your explanation is very helpful and much appreciated. 👍🏻
